### PR TITLE
[Docs] Improved install instructions

### PR DESCRIPTION
**Pull request by Wulfheart**
Related to #34.

### CODE REVIEW

**Review by regnerisch — CHANGES_REQUESTED** [review]
Isn't that the same as https://github.com/regnerisch/laravel-beyond/blob/master/README.md#set-up-a-domain-driven-application?

**Comment by Wulfheart** [comment]
Ah yes. I oversaw it. But I believe it should be moved upwards.

**Comment by regnerisch** [comment]
Yes it should. Please keep your change but remove the section at the end of the README. :)

**Comment by Wulfheart** [comment]
@regnerisch done.

**Pull request merged**
